// Code generated by mockery v2.6.0. DO NOT EDIT.

package api

import mock "github.com/stretchr/testify/mock"

// MockUI is an autogenerated mock type for the UI type
type MockUI struct {
	mock.Mock
}

// Refresh provides a mock function with given fields:
func (_m *MockUI) Refresh() {
	_m.Called()
}

// TableWidget provides a mock function with given fields:
func (_m *MockUI) TableWidget() TableWidget {
	ret := _m.Called()

	var r0 TableWidget
	if rf, ok := ret.Get(0).(func() TableWidget); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(TableWidget)
		}
	}

	return r0
}
